version: "3"

services:
  linesprovider:
    image: antonboom/lines-provider
    ports:
      - "8000:8000"
    networks:
      - fullstack

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: LinesStorage
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack

  linesprocessor:
    build: .
    ports:
    - "8080:8080"
    - "9090:9090"
    environment:
      - HTTP_SERVER_ADDR=0.0.0.0
      - GRPC_SERVER_ADDR=0.0.0.0
      - BASEBALL_INT=15
      - FOOTBALL_INT=15
      - SOCCER_INT=15
      - LOG_LEVEL=trace
    depends_on:
      - linesprovider
      - db
    links:
      - "linesprovider"
      - "db"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge