// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: subscribeservice.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sport        []string `protobuf:"bytes,1,rep,name=sport,proto3" json:"sport,omitempty"`
	TimeInterval int32    `protobuf:"varint,2,opt,name=timeInterval,proto3" json:"timeInterval,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscribeservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_subscribeservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_subscribeservice_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSport() []string {
	if x != nil {
		return x.Sport
	}
	return nil
}

func (x *Request) GetTimeInterval() int32 {
	if x != nil {
		return x.TimeInterval
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SportName  string  `protobuf:"bytes,1,opt,name=SportName,proto3" json:"SportName,omitempty"`
	SportRatio float32 `protobuf:"fixed32,2,opt,name=SportRatio,proto3" json:"SportRatio,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscribeservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_subscribeservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_subscribeservice_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSportName() string {
	if x != nil {
		return x.SportName
	}
	return ""
}

func (x *Response) GetSportRatio() float32 {
	if x != nil {
		return x.SportRatio
	}
	return 0
}

var File_subscribeservice_proto protoreflect.FileDescriptor

var file_subscribeservice_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x43, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x32, 0x50, 0x0a, 0x07, 0x47, 0x52, 0x50, 0x43, 0x41, 0x70, 0x69, 0x12, 0x45, 0x0a, 0x16,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x6e, 0x53, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_subscribeservice_proto_rawDescOnce sync.Once
	file_subscribeservice_proto_rawDescData = file_subscribeservice_proto_rawDesc
)

func file_subscribeservice_proto_rawDescGZIP() []byte {
	file_subscribeservice_proto_rawDescOnce.Do(func() {
		file_subscribeservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_subscribeservice_proto_rawDescData)
	})
	return file_subscribeservice_proto_rawDescData
}

var file_subscribeservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscribeservice_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: protobuf.Request
	(*Response)(nil), // 1: protobuf.Response
}
var file_subscribeservice_proto_depIdxs = []int32{
	0, // 0: protobuf.GRPCApi.SubscribeOnSportsLines:input_type -> protobuf.Request
	1, // 1: protobuf.GRPCApi.SubscribeOnSportsLines:output_type -> protobuf.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscribeservice_proto_init() }
func file_subscribeservice_proto_init() {
	if File_subscribeservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_subscribeservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subscribeservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subscribeservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscribeservice_proto_goTypes,
		DependencyIndexes: file_subscribeservice_proto_depIdxs,
		MessageInfos:      file_subscribeservice_proto_msgTypes,
	}.Build()
	File_subscribeservice_proto = out.File
	file_subscribeservice_proto_rawDesc = nil
	file_subscribeservice_proto_goTypes = nil
	file_subscribeservice_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GRPCApiClient is the client API for GRPCApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCApiClient interface {
	SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (GRPCApi_SubscribeOnSportsLinesClient, error)
}

type gRPCApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCApiClient(cc grpc.ClientConnInterface) GRPCApiClient {
	return &gRPCApiClient{cc}
}

func (c *gRPCApiClient) SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (GRPCApi_SubscribeOnSportsLinesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCApi_serviceDesc.Streams[0], "/protobuf.GRPCApi/SubscribeOnSportsLines", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCApiSubscribeOnSportsLinesClient{stream}
	return x, nil
}

type GRPCApi_SubscribeOnSportsLinesClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type gRPCApiSubscribeOnSportsLinesClient struct {
	grpc.ClientStream
}

func (x *gRPCApiSubscribeOnSportsLinesClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCApiSubscribeOnSportsLinesClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPCApiServer is the server API for GRPCApi service.
type GRPCApiServer interface {
	SubscribeOnSportsLines(GRPCApi_SubscribeOnSportsLinesServer) error
}

// UnimplementedGRPCApiServer can be embedded to have forward compatible implementations.
type UnimplementedGRPCApiServer struct {
}

func (*UnimplementedGRPCApiServer) SubscribeOnSportsLines(GRPCApi_SubscribeOnSportsLinesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOnSportsLines not implemented")
}

func RegisterGRPCApiServer(s *grpc.Server, srv GRPCApiServer) {
	s.RegisterService(&_GRPCApi_serviceDesc, srv)
}

func _GRPCApi_SubscribeOnSportsLines_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCApiServer).SubscribeOnSportsLines(&gRPCApiSubscribeOnSportsLinesServer{stream})
}

type GRPCApi_SubscribeOnSportsLinesServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type gRPCApiSubscribeOnSportsLinesServer struct {
	grpc.ServerStream
}

func (x *gRPCApiSubscribeOnSportsLinesServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCApiSubscribeOnSportsLinesServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GRPCApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.GRPCApi",
	HandlerType: (*GRPCApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnSportsLines",
			Handler:       _GRPCApi_SubscribeOnSportsLines_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "subscribeservice.proto",
}
