// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GRPCApiClient is the client API for GRPCApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCApiClient interface {
	SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (GRPCApi_SubscribeOnSportsLinesClient, error)
}

type gRPCApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCApiClient(cc grpc.ClientConnInterface) GRPCApiClient {
	return &gRPCApiClient{cc}
}

var gRPCApiSubscribeOnSportsLinesStreamDesc = &grpc.StreamDesc{
	StreamName:    "SubscribeOnSportsLines",
	ServerStreams: true,
	ClientStreams: true,
}

func (c *gRPCApiClient) SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (GRPCApi_SubscribeOnSportsLinesClient, error) {
	stream, err := c.cc.NewStream(ctx, gRPCApiSubscribeOnSportsLinesStreamDesc, "/protobuf.GRPCApi/SubscribeOnSportsLines", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCApiSubscribeOnSportsLinesClient{stream}
	return x, nil
}

type GRPCApi_SubscribeOnSportsLinesClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type gRPCApiSubscribeOnSportsLinesClient struct {
	grpc.ClientStream
}

func (x *gRPCApiSubscribeOnSportsLinesClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCApiSubscribeOnSportsLinesClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPCApiService is the service API for GRPCApi service.
// Fields should be assigned to their respective handler implementations only before
// RegisterGRPCApiService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type GRPCApiService struct {
	SubscribeOnSportsLines func(GRPCApi_SubscribeOnSportsLinesServer) error
}

func (s *GRPCApiService) subscribeOnSportsLines(_ interface{}, stream grpc.ServerStream) error {
	return s.SubscribeOnSportsLines(&gRPCApiSubscribeOnSportsLinesServer{stream})
}

type GRPCApi_SubscribeOnSportsLinesServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type gRPCApiSubscribeOnSportsLinesServer struct {
	grpc.ServerStream
}

func (x *gRPCApiSubscribeOnSportsLinesServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCApiSubscribeOnSportsLinesServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterGRPCApiService registers a service implementation with a gRPC server.
func RegisterGRPCApiService(s grpc.ServiceRegistrar, srv *GRPCApiService) {
	srvCopy := *srv
	if srvCopy.SubscribeOnSportsLines == nil {
		srvCopy.SubscribeOnSportsLines = func(GRPCApi_SubscribeOnSportsLinesServer) error {
			return status.Errorf(codes.Unimplemented, "method SubscribeOnSportsLines not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "protobuf.GRPCApi",
		Methods:     []grpc.MethodDesc{},
		Streams: []grpc.StreamDesc{
			{
				StreamName:    "SubscribeOnSportsLines",
				Handler:       srvCopy.subscribeOnSportsLines,
				ServerStreams: true,
				ClientStreams: true,
			},
		},
		Metadata: "proto/subscribeservice.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewGRPCApiService creates a new GRPCApiService containing the
// implemented methods of the GRPCApi service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewGRPCApiService(s interface{}) *GRPCApiService {
	ns := &GRPCApiService{}
	if h, ok := s.(interface {
		SubscribeOnSportsLines(GRPCApi_SubscribeOnSportsLinesServer) error
	}); ok {
		ns.SubscribeOnSportsLines = h.SubscribeOnSportsLines
	}
	return ns
}

// UnstableGRPCApiService is the service API for GRPCApi service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableGRPCApiService interface {
	SubscribeOnSportsLines(GRPCApi_SubscribeOnSportsLinesServer) error
}
